### ISSUE TITLE
How to test the ISIC17 and ISIC18 datasets

### ISSUE THREAD

**Issue by zhouhao028** [gndlwch2w/msvm-unet#4]
Hello, author! Thank you for your work. I want to train and test ISIC17 and ISIC18 in MSVM-Unet, but ISIC17 and ISIC18 need to input masks. How can I add mask input in msvm? Thank you.

**Comment by zhouhao028** [comment]
Hello, author! I run train_acdc.py according to your steps and it will report an error。[rank1]: Traceback (most recent call last):
[rank1]:   File "/data0/zh/msvm-unet/train_acdc.py", line 228, in <module>
[rank1]:     train("log/msvm-unet-acdc")
[rank1]:   File "/data0/zh/msvm-unet/train_acdc.py", line 223, in train
[rank1]:     trainer.fit(model, ckpt_path=None)
[rank1]:   File "/home/zh/.conda/envs/vmunet/lib/python3.8/site-packages/lightning/pytorch/trainer/trainer.py", line 543, in fit
[rank1]:     call._call_and_handle_interrupt(
[rank1]:   File "/home/zh/.conda/envs/vmunet/lib/python3.8/site-packages/lightning/pytorch/trainer/call.py", line 43, in _call_and_handle_interrupt
[rank1]:     return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
[rank1]:   File "/home/zh/.conda/envs/vmunet/lib/python3.8/site-packages/lightning/pytorch/strategies/launchers/subprocess_script.py", line 105, in launch
[rank1]:     return function(*args, **kwargs)
[rank1]:   File "/home/zh/.conda/envs/vmunet/lib/python3.8/site-packages/lightning/pytorch/trainer/trainer.py", line 579, in _fit_impl
[rank1]:     self._run(model, ckpt_path=ckpt_path)
[rank1]:   File "/home/zh/.conda/envs/vmunet/lib/python3.8/site-packages/lightning/pytorch/trainer/trainer.py", line 986, in _run
[rank1]:     results = self._run_stage()
[rank1]:   File "/home/zh/.conda/envs/vmunet/lib/python3.8/site-packages/lightning/pytorch/trainer/trainer.py", line 1028, in _run_stage
[rank1]:     self._run_sanity_check()
[rank1]:   File "/home/zh/.conda/envs/vmunet/lib/python3.8/site-packages/lightning/pytorch/trainer/trainer.py", line 1057, in _run_sanity_check
[rank1]:     val_loop.run()
[rank1]:   File "/home/zh/.conda/envs/vmunet/lib/python3.8/site-packages/lightning/pytorch/loops/utilities.py", line 182, in _decorator
[rank1]:     return loop_run(self, *args, **kwargs)
[rank1]:   File "/home/zh/.conda/envs/vmunet/lib/python3.8/site-packages/lightning/pytorch/loops/evaluation_loop.py", line 110, in run
[rank1]:     self.setup_data()
[rank1]:   File "/home/zh/.conda/envs/vmunet/lib/python3.8/site-packages/lightning/pytorch/loops/evaluation_loop.py", line 166, in setup_data
[rank1]:     dataloaders = _request_dataloader(source)
[rank1]:   File "/home/zh/.conda/envs/vmunet/lib/python3.8/site-packages/lightning/pytorch/trainer/connectors/data_connector.py", line 325, in _request_dataloader
[rank1]:     return data_source.dataloader()
[rank1]:   File "/home/zh/.conda/envs/vmunet/lib/python3.8/site-packages/lightning/pytorch/trainer/connectors/data_connector.py", line 289, in dataloader
[rank1]:     return call._call_lightning_module_hook(self.instance.trainer, self.name, pl_module=self.instance)
[rank1]:   File "/home/zh/.conda/envs/vmunet/lib/python3.8/site-packages/lightning/pytorch/trainer/call.py", line 159, in _call_lightning_module_hook
[rank1]:     output = fn(*args, **kwargs)
[rank1]:   File "/data0/zh/msvm-unet/train_acdc.py", line 97, in val_dataloader
[rank1]:     return data.DataLoader(self.val_dataset, **vdl)
[rank1]:   File "/home/zh/.conda/envs/vmunet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
[rank1]:     raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
[rank1]: AttributeError: 'ACDC' object has no attribute 'val_dataset'
[rank: 1] Child process with PID 2239044 terminated with code 1. Forcefully terminating all other processes to avoid zombies 🧟
Killed。The specific reason should be:AttributeError: 'ACDC' object has no attribute 'val_dataset'。

**Comment by gndlwch2w** [comment]
Thank you for extending our work to other datasets. The following are some things that may need to be considered and modified when expanding to the ISIC dataset:
- [dataset_acdc.py](https://github.com/gndlwch2w/msvm-unet/blob/main/dataset_acdc.py) and [dataset_synapse.py](https://github.com/gndlwch2w/msvm-unet/blob/main/dataset_synapse.py) **do not support 2D RGB input directly**, only support 2D grayscale npz files or 3D h5 files.
- The `validation_step` in [train_acdc.py](https://github.com/gndlwch2w/msvm-unet/blob/main/train_acdc.py) and [train_synapse.py](https://github.com/gndlwch2w/msvm-unet/blob/main/train_synapse.py) **only supports 3D slice testing** and needs to be adapted to 2D RGB input.
-  [inference.py](https://github.com/gndlwch2w/msvm-unet/blob/main/inference.py) cannot be used directly to test the model obtained from the ISIC dataset, it only supports testing 3D slices such as ACDC and Synapse.
